#spring:
#  application:
#    name: auth-service
#server:
#  port: 9100
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://registry:8761/eureka
#      defaultZone: ${EUREKA_SERVER:http://registry:8761/eureka}